### ISSUE TITLE
Add FM-index functions to saparate .py file(s)

### ISSUE THREAD

**Issue by vladimirkovacevic** [mspaic96/GenomeInformatics#2]
...and import them in the notebook

**Comment by mspaic96** [comment]
I have done it first like that. I used pip install ipynb and    from ipynb.fs.full.<notebook_name> import <function_name> to import it , but somehow error happened in the middle of project and i wasnt able to import from one to another file.  So I moved everything in one notebook. Every function that is wriiten by me has a assertion under it, if there is no assertion below function it is from sais alghorithm.
